### ISSUE TITLE
WotLK Classic Error

### ISSUE THREAD

**Issue by jahirahdk** [Numynum/MacroToolkit#22] opened 2023-02-06 20:31 UTC
2x MacroToolkit/MacroToolkit.lua:154: attempt to index field 'LinkToButton' (a nil value)
[string "@MacroToolkit/MacroToolkit.lua"]:154: in function `eventHandler'
[string "@MacroToolkit/modules/initialise.lua"]:15: in function <MacroToolkit/modules/initialise.lua:15>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:385: in function `UIParentLoadAddOn'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:456: in function `TradeSkillFrame_LoadUI'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:1253: in function <Interface_Wrath/FrameXML/UIParent.lua:756>
[string "=[C]"]: in function `CastSpell'
[string "@FrameXML/SpellBookFrame.lua"]:363: in function `SpellButton_OnClick'
[string "*SpellBookFrame.xml:163_OnClick"]:4: in function <[string "*SpellBookFrame.xml:163_OnClick"]:1>

Locals:
self = <table> {
 FindShortest = <function> defined @MacroToolkit/modules/parser.lua:13
 defaults = <table> {
 }
 RunCommands = <function> defined @MacroToolkit/modules/macrobroker.lua:81
 BindingButtonOnClick = <function> defined @MacroToolkit/modules/bindingframe.lua:225
 IsTarget = <function> defined @MacroToolkit/modules/parser.lua:249
 target = "/target"
 UpdateErrors = <function> defined @MacroToolkit/MacroToolkit.lua:689
 origMTText = MacroFrameText {
 }
 CreateBrokerObject = <function> defined @MacroToolkit/modules/macrobroker.lua:101
 SetBinding = <function> defined @MacroToolkit/modules/bindingframe.lua:242
 eventHandler = <function> defined @MacroToolkit/MacroToolkit.lua:94
 FindScript = <function> defined @MacroToolkit/MacroToolkit.lua:448
 skinned = <table> {
 }
 UpdateIcon = <function> defined @MacroToolkit/modules/mainframe.lua:1040
 ClearAllMacros = <function> defined @MacroToolkit/MacroToolkit.lua:292
 nummiscicons = 5689
 FormatMacro = <function> defined @MacroToolkit/MacroToolkit.lua:477
 Skin = <function> defined @MacroToolkit/modules/elvskin.lua:6
 CombatMessage = <function> defined @MacroToolkit/MacroToolkit.lua:1219
 CreateCopyFrame = <function> defined @MacroToolkit/modules/copyframe.lua:6
 click = "/click"
 GetLastBackupDate = <function> defined @MacroToolkit/modules/restoreframe.lua:242
 clist = <table> {
 }
 SetLastBackupDate = <function> defined @MacroToolkit/MacroToolkit.lua:1165
 itemicons = <table> {
 }
 achicons = <table> {
 }
 PopupButtonOnClick = <function> defined @MacroToolkit/modules/popupframe.lua:520
 numabilityicons = 0
 UpdateInterfaceOptions = <function> defined @MacroToolkit/modules/options.lua:901
 UpdateIconCount = <function> defined @MacroToolkit/modules/popupframe.lua:555
 Eval = <function> defined @MacroToolkit/modules/macrobroker.lua:69
 SaveMacro = <function> defined @MacroToolkit/MacroToolkit.lua:1092
 UpdateBindingFrame = <function> defined @MacroToolkit/modules/bindingframe.lua:269
 ReceiveMacro = <function> defined @MacroToolkit/modules/shareframe.lua:217
 gosmall = <function> defined @MacroToolkit/modules/popupframe.lua:348
 MTPF = MacroToolkitPopup {
 }
 CreateBuilderFrame = <function> defined @MacroToolkit/modules/builderframe.lua:16
 Spells = <table> {
 }
 AIS = <table> {
 }
 FindComment = <function> defined @MacroToolkit/modules/parser.lua:670
 UpdateCharLimit = <function> defined @MacroToolkit/MacroToolkit.lua:671
 IsCast = <function> defined @MacroToolkit/modules/parser.lua:247
 SelectTexture = <function> defined @MacroToolkit/modules/popupframe.lua:461
 CreateSecureActionButton = <function> defined @MacroToolkit/modules/mainframe.lua:1092
 ParseMacro = <function> defined @MacroToolkit/modules/parser.lua:675
 L = <table> {
 }
 OptionsFrame = Frame {
 }
 GetSpellorMacroIconInfo = <function> defined @MacroToolkit/modules/popupframe.lua:429
 RGBToHex = <function> defined @MacroToolkit/MacroToolkit.lua:321
 CreateScriptFrame = <function> defined @MacroToolkit/modules/scriptframe.lua:6
 MACRO_ICON_FILENAMES = <table> {
 }
 spellicons = <table> {
 }
 ShowShortened = <function> defined @MacroToolkit/MacroToolkit.lua:450
 conditions = <table> {
 }
 ShowDetails = <function> defined @MacroToolkit/MacroToolkit.lua:1072
 ShortenMacro = <function> defined @MacroToolkit/modules/parser.lua:476
 GetBackupTitle = <function> defined @MacroToolkit/modules/restoreframe.lua:161
 slots = <table> {
 }
 BuildCommandList = <function>

**Comment by Numynum** [comment] 2023-02-06 23:35
duplicate of #21

**Closed by Numynum** 2023-02-06 23:35 UTC
